/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Paresh shah
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    int i;
    Thread t;
    boolean choice;
    ArrayList<JPanel> arr;
  //  ArrayList<XChartPanel> charts;
    public Student() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
    }
     public Student(boolean bool) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.choice=bool;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slide2 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        stdPanel2 = new javax.swing.JPanel();
        stdPanel2.setVisible(false);
        jLabel1 = new javax.swing.JLabel();
        stdPanel1 = new javax.swing.JPanel();
        stdPanel1.setVisible(false);
        jLabel2 = new javax.swing.JLabel();
        stdchart1 = new javax.swing.JPanel();
        stdchart1.setVisible(false);
        stdchart2 = new javax.swing.JPanel();
        stdchart2.setVisible(false);
        stdchart3 = new javax.swing.JPanel();
        stdchart3.setVisible(false);
        stdchart4 = new javax.swing.JPanel();
        stdchart4.setVisible(false);
        stdchart5 = new javax.swing.JPanel();
        stdchart5.setVisible(false);
        comchart1 = new javax.swing.JPanel();
        comchart1.setVisible(false);
        comchart2 = new javax.swing.JPanel();
        comchart2.setVisible(false);
        comchart5 = new javax.swing.JPanel();
        comchart5.setVisible(false);
        comchart6 = new javax.swing.JPanel();
        comchart6.setVisible(false);
        comchart7 = new javax.swing.JPanel();
        comchart7.setVisible(false);
        stdPanel3 = new javax.swing.JPanel();
        stdPanel3.setVisible(false);
        jLabel3 = new javax.swing.JLabel();
        stdPanel4 = new javax.swing.JPanel();
        stdPanel4.setVisible(false);
        jLabel4 = new javax.swing.JLabel();
        stdPanel5 = new javax.swing.JPanel();
        stdPanel5.setVisible(false);
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        slide2.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout slide2Layout = new javax.swing.GroupLayout(slide2);
        slide2.setLayout(slide2Layout);
        slide2Layout.setHorizontalGroup(
            slide2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        slide2Layout.setVerticalGroup(
            slide2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1366, 748));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1366, 748));

        stdPanel2.setBackground(new java.awt.Color(255, 255, 255));
        stdPanel2.setLayout(new javax.swing.BoxLayout(stdPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stdPanel2.add(jLabel1);

        stdPanel1.setBackground(new java.awt.Color(255, 255, 255));
        stdPanel1.setLayout(new javax.swing.BoxLayout(stdPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stdPanel1.add(jLabel2);

        stdchart1.setLayout(new javax.swing.BoxLayout(stdchart1, javax.swing.BoxLayout.LINE_AXIS));

        stdchart2.setLayout(new javax.swing.BoxLayout(stdchart2, javax.swing.BoxLayout.LINE_AXIS));

        stdchart3.setLayout(new javax.swing.BoxLayout(stdchart3, javax.swing.BoxLayout.LINE_AXIS));

        stdchart4.setLayout(new javax.swing.BoxLayout(stdchart4, javax.swing.BoxLayout.LINE_AXIS));

        stdchart5.setLayout(new javax.swing.BoxLayout(stdchart5, javax.swing.BoxLayout.LINE_AXIS));

        comchart1.setLayout(new javax.swing.BoxLayout(comchart1, javax.swing.BoxLayout.LINE_AXIS));

        comchart2.setLayout(new javax.swing.BoxLayout(comchart2, javax.swing.BoxLayout.LINE_AXIS));

        comchart5.setLayout(new javax.swing.BoxLayout(comchart5, javax.swing.BoxLayout.LINE_AXIS));

        comchart6.setLayout(new javax.swing.BoxLayout(comchart6, javax.swing.BoxLayout.LINE_AXIS));

        comchart7.setLayout(new javax.swing.BoxLayout(comchart7, javax.swing.BoxLayout.LINE_AXIS));

        stdPanel3.setLayout(new javax.swing.BoxLayout(stdPanel3, javax.swing.BoxLayout.LINE_AXIS));
        stdPanel3.add(jLabel3);

        stdPanel4.setLayout(new javax.swing.BoxLayout(stdPanel4, javax.swing.BoxLayout.LINE_AXIS));
        stdPanel4.add(jLabel4);

        stdPanel5.setLayout(new javax.swing.BoxLayout(stdPanel5, javax.swing.BoxLayout.LINE_AXIS));
        stdPanel5.add(jLabel5);

        jLayeredPane1.setLayer(stdPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 131, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdchart1, javax.swing.GroupLayout.DEFAULT_SIZE, 1731, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdchart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdchart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdchart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdchart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(comchart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(comchart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(comchart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(comchart6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(comchart7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 866, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdchart1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(stdchart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(stdchart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(stdchart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(stdchart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(comchart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(comchart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(comchart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(comchart6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(comchart7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 484, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 485, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 185, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 485, Short.MAX_VALUE)))
        );

        jButton1.setText("PLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("STOP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(778, 778, 778)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            animate();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

        // Adding charts to slide arraylist
    private JPanel addNoOfVolumes(JPanel panel)
    {
        NoOfVolumes chart=new NoOfVolumes();
        
        try {
            JPanel temp= chart.getPanel();
            panel.add(temp);
            panel.validate();
        } catch (IOException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
        return panel;
        
    }
    private JPanel addNumberOfBooks(JPanel panel)
    {
        NumberOfBooks chart=new NumberOfBooks();
        
        JPanel temp= chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
        
    }
   
    private JPanel addUsers(JPanel panel) throws IOException
    {
         Users chart=new Users();
        
        JPanel temp= chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
    
    private JPanel addJournalsIssuedPerYear(JPanel panel) throws IOException
    {
        JournalsIssuedPerYear chart=new JournalsIssuedPerYear();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
    
      private JPanel addPeriodicalsPerYear(JPanel panel) throws IOException
    {
        PeriodicalsPerYear chart=new PeriodicalsPerYear();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
      
      private JPanel addLibraryArea(JPanel panel) throws IOException
    {
        LibraryArea chart=new LibraryArea();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }  
        private JPanel addExpenditureOnBook(JPanel panel) throws IOException
    {
        ExpenditureOnBook chart=new ExpenditureOnBook();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
             private JPanel addExpenditureDistribution(JPanel panel) throws IOException, SQLException
    {
        ExpenditureDistribution chart=new ExpenditureDistribution();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
   
             
    private JPanel addLibraryExpenditurePerYear(JPanel panel) throws IOException, SQLException
    {
        LibraryExpenditurePerYear chart=new LibraryExpenditurePerYear();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
      //Making the slide arraylist for students
    public ArrayList<JPanel> makeSlidesStudents() throws IOException
    {
        ArrayList<JPanel> arr=new ArrayList<>();
        
        //arr.add(stdPanel1);
        //arr.add(stdPanel2);
        //arr.add(stdPanel3);
        //arr.add(stdPanel4);
        //arr.add(stdPanel5);
        arr.add(this.addNoOfVolumes(stdchart1));
        arr.add(this.addNumberOfBooks(stdchart2));
        arr.add(this.addJournalsIssuedPerYear(stdchart3));
        arr.add(this.addPeriodicalsPerYear(stdchart4));
        arr.add(this.addUsers(stdchart5));
        return arr;
    }
    
    
    public ArrayList<JPanel> makeSlidesCommittee() throws IOException, SQLException
    {
        ArrayList<JPanel> arr=new ArrayList<>();
        arr.add(this.addExpenditureDistribution(comchart1));
        arr.add(this.addExpenditureOnBook(comchart2));
        arr.add(this.addLibraryExpenditurePerYear(comchart5));
        arr.add(this.addLibraryArea(comchart6));
        arr.add(this.addUsers(comchart7));
        return arr;
    }
    //Main function for starting the slide show
    public void animate() throws IOException, SQLException
    {
        
        if(this.choice==false)
        {
            this.arr=this.makeSlidesStudents();
        }
        else if(this.choice==true)
        {
          this.arr=this.makeSlidesCommittee();
        }
        for(JPanel panel:arr){
            System.out.println(panel.toString());
        }
        int size;
        size = arr.size();
            t=new Thread(){
           
           int i=0;
            @Override
            public void run()
            {
                while(true)
                {     
                    
                    System.out.println("Working");
                    try {
                     t.sleep(6000);
                    } catch (InterruptedException ex) {
                     Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for(int j=0;j<size;j++)
                    {
                         if(j==i)
                             arr.get(j).setVisible(true);
                        else
                             arr.get(j).setVisible(false);
                    }  
                
                    jLayeredPane1.repaint();
                    i=(++i)%size;
                    
                }
            }
        };
            t.start();
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel comchart1;
    private javax.swing.JPanel comchart2;
    private javax.swing.JPanel comchart5;
    private javax.swing.JPanel comchart6;
    private javax.swing.JPanel comchart7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel slide2;
    private javax.swing.JPanel stdPanel1;
    private javax.swing.JPanel stdPanel2;
    private javax.swing.JPanel stdPanel3;
    private javax.swing.JPanel stdPanel4;
    private javax.swing.JPanel stdPanel5;
    private javax.swing.JPanel stdchart1;
    private javax.swing.JPanel stdchart2;
    private javax.swing.JPanel stdchart3;
    private javax.swing.JPanel stdchart4;
    private javax.swing.JPanel stdchart5;
    // End of variables declaration//GEN-END:variables
}
